version: "2"

services:
  app:
    container_name: "wildfly-container"
    image: "frizio/wildfly"
    environment:
      - WILDFLY_USER=admin
      - WILDFLY_PASS=password1;
      - DB_NAME=test
      - DB_USER=wildfly_user
      - DB_PASS=password1;
      - DB_URI=db:3306
    ports:
      - "8080:8080" # application
      - "9990:9990" # admin console
    depends_on:
      - db
  db:
    container_name: "mysql-w-container"
    image: "mysql:8.0.18"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=wildfly_user
      - MYSQL_PASSWORD=password1;
      - MYSQL_ROOT_PASSWORD=supersecret
    volumes:
      #- $HOME/Docker-Data/wildfly-mysql-data/db/init/:/docker-entrypoint-initdb.d/ # init database
      #- $HOME/Docker-Data/wildfly-mysql-data/db/data/:/var/lib/mysql/              # data storage
      - db-init/:/docker-entrypoint-initdb.d/
      - db-data/:/var/lib/mysql/
    ports:
      - "3306:3306"

networks:
    default:
        driver: bridge

volumes:
  db-init:
    driver: local
  db-data:
    driver: local